version: "3.8"

services:
  backend:
    container_name: quicknote-backend
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - network_quicknote

  frontend:
    container_name: quicknote-frontend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://quicknote-backend:8000/api
    depends_on:
      - backend
    networks:
      - network_quicknote

  db:
    container_name: quicknote-database
    image: postgres:17
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
    networks:
      - network_quicknote
    ports:
      - :5432

volumes:
  postgres-data:

networks:
  network_quicknote:
    driver: bridge
