# Generated by Django 5.1.1 on 2024-10-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pos_x',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='pos_y',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
