# Generated by Django 5.1.1 on 2024-10-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_note_pos_x_note_pos_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dark', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
