# Generated by Django 5.1.1 on 2024-10-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mode_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_size', models.PositiveIntegerField(blank=True, default=25, null=True)),
            ],
        ),
    ]
